name: Run tests on feature branches


on: 
  push:
    branches:
      'feature/*'

jobs:
  run-ui-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1

      - name: Run tests
        run: yarn install && yarn cypress run --spec cypress/e2e/ListsFeature.cy.js --reporter mochawesome
    
