name: Run tests on main and feature branches

on:
  push:
    branches:
      - main
      - 'feature/*'

jobs:
  run-ui-tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '14' # Specify the Node.js version you want to use

      - name: Install dependencies
        run: yarn install

      - name: Run tests
        run: yarn cy:run --spec "cypress/e2e/**/*.cy.js" --reporter mochawesome
